---

- name: download ipfs
  get_url: url={{ ipfsurl }} dest={{ download_dir }}/{{ ipfssrc }}.tar.gz

- name: unpack ipfs
  unarchive: src={{ download_dir }}/{{ ipfssrc }}.tar.gz dest={{ download_dir }}/{{ ipfssrc }}

- name: move ipfs to bin dir
  copy: src={{ download_dir }}/{{ ipfssrc }}/go-ipfs/ipfs dest=/usr/local/bin/ipfs owner={{ ipfs_user }} group={{ ipfs_group}} mode=0755

- include: debian-init.yml
  when: ansible_os_family == 'Debian'

- include: redhat-init.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure ipfs is started
  service: name=ipfs state=started enabled=yes
