---

- name: Ensure dependencies are installed
  include: dependencies.yml

- name: Ensure download directory is present
  file: path={{ download_dir }} state=directory

- name: Ensure source directory is present
  file: path={{ download_dir }}/{{ ipfssrc }} state=directory

- include: redhat-deps.yml
  when: ansible_os_family == 'RedHat'

- include: debian-deps.yml
  when: ansible_os_family == 'Debian'

- name: Create ipfs group
  group: name={{ ipfs_group }} state=present

- name: Create ipfs user
  user: name={{ ipfs_user }} state=present groups={{ ipfs_group }}

- include: install-ipfs.yml

- name: initialize ipfs
  command: creates="/home/{{ ipfs_user }}/.ipfs/version" su - "{{ ipfs_user }}" /bin/sh -c "/usr/local/bin/ipfs init"
  register: init

- debug: var=init

# - name: register log for debug purpose
#   command: cat /var/log/ipfs.log
#   register: result
#
# - debug: var=result


- name: debug ipfs log
  command: cat /var/log/ipfs.log
  register: baby

- name: debug ipfs log
  command: cat /var/log/ipfs.err
  register: baby

- debug: var=baby
- debug: var=boomer


- name: Ensure ipfs is started
  service: name=ipfs state=started enabled=yes
